/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mehdi' at '31/12/16 12:08 AM' with Gradle 3.2.1
 *
 * @author mehdi, @date 31/12/16 12:08 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
